name: autonotify_observe
version: 1.0.0+8
author: Vittorio Ballestra (Drafintech s.r.l.) <vittorio.ballestra@gmail.com>
description: observe auto notify support for Polymer 1.0
homepage : https://github.com/dam0vm3nt/autonotify_observe
environment:
 sdk: ">=1.8.0 <2.0.0"

dependencies:
 polymer: ">=1.0.0-rc.12"
 observe:
  git:
   ref: reflectable
   url: https://github.com/dam0vm3nt/observe.git
 barback: any
# reflectable: ">=0.4.0 <0.6.0"
# web_components: ^0.12.0
 polymer_autonotify: "^1.0.0"

dev_dependencies:
 test: any

# TODO : move tests to observe
transformers:
- autonotify_observe:
   entry_points:
    - test/autonotify_test.html
- test/pub_serve:
   $include: test/**_test{.*,}.dart

# Comment befor publish
#dependency_overrides:
#  observe:
#   path: ../observe
# polymer_autonotify:
#  path: ../polymer_autonotify


