name: demo_polymer_autonotify
description: Demo project for polymer autonotify
version: 0.0.1
author: Vittorio Ballestra <vittorio.ballestra@drafintech.it>
homepage: https://github.com/dam0vm3nt/polymer_autonotify
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
 polymer_elements: ">=1.0.0-rc.3"
 autonotify_observe: "^1.0.0-rc.10"
 browser: any
 custom_elements: any
dev_dependencies:
 test: "0.12.15+1"


dependency_overrides:
 polymer_autonotify:
  path: ../../polymer_autonotify
 polymer_interop:
  path: ../../polymer_interop
 polymer:
  path: ../../polymer-dart
#autonotify_observe:
#  path: ..


transformers:
- autonotify_observe:
    entry_points:
    - web/index.html
    - test/autonotify_test.html

- test/pub_serve:
    $include: test/**_test{.*,}.dart
